title: Applied Inference Group
description: Biostatistical modeling and advanced statistical consulting for research-driven organizations.
remote_theme: mmistakes/so-simple-theme
plugins:
  - jekyll-remote-theme
